### ISSUE TITLE
External Link text optional

### ISSUE THREAD

**Issue by beliolfa** [pdewit/nova-external-url#2]
Hi, nice package! I was about to make this field but did a research before!

I am using this in a Spanish localized app but this `External Link` text is imposible to change.

Can you make it configurable and, even better, optional to display?

Nice work.

**Comment by agustinprod** [comment]
+1, also, it can be useful in case you want to add several links to a single resource.

**Comment by niladam** [comment]
@disitec @killgt - use the `linkText` function to change `External Link`, like so:

```php
...

ExternalUrl::make('Slug', 'slug', function () {
    return url($this->slug);
    })->linkText($this->slug),

...
```

Obviously - you can pass anything to `linkText`.

**Comment by niladam** [comment]
Apparently this has been solved in #3 by @iaK 👍  :) -- didn't realise this wasn't available when @disitec opened the issue.

**Comment by iaK** [comment]
Close this maybe @pdewit?

**Comment by pdewit** [comment]
Yep, thanks.
